---
title: "PopTrendGraphs"
author: "Katie Birchard"
date: '2018-04-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Making trend graphs for climate for every population:

```{r}
climtrend <- read.csv("ClimTrendData.csv") #loading in temp data
head(climtrend)
realcoords <- read.csv("mec12972-sup-0001-TableS1-S5.csv") #loading in actual coordinates (non-rounded) in case I need them
head(realcoords)

View(climtrend)

climtrend$RealLat <- realcoords$Latitude #adding actual coordinates to dataset
climtrend$Reallong <- realcoords$Longitude

range(climtrend$pastTemp) #-6.07, 9.75
range(climtrend$CurTemp) #-6.3, 6.8
range(climtrend$FutTemp) #-3.1, 9.2

require(ggplot2) #need this to make the graph
require(reshape2) #need this to melt the data so past, current, and future temp are in the same column

df <- melt(climtrend, id.vars = c("pastTemp", "CurTemp", "FutTemp"), variable.name = "code") #trying to melt the data and failing

ggplot(df, aes(pastTemp, value)) + geom_point(aes(colour=code)) #trying to plot the data, but failing
ggplot(df, aes(CurTemp, value)) + geom_point(aes(colour=code))
ggplot(df, aes(FutTemp, value)) + geom_point(aes(colour=code))

data <- data.frame(climtrend$code, climtrend$pastTemp, climtrend$CurTemp, climtrend$FutTemp)
View(data) #putting data columns I want for my graph into a data frame

data1 <- melt(data, id.vars=c("climtrend.code")) #melting so that temperature is now a column, and timepoint is now a column
View(data1)

for (i in nrow(data1$variable)){ #making loop to rename variables to something more aesthetic
	if (data1$variable[i] == "climtrend.pastTemp") {
		data1$variable[i] <- "Past"
	}
	if (data1$variable[i] == "climtrend.CurTemp") {
		data1$variable[i] <- "Present"
	}
	if (data1$variable[i] == "climtrend.FutTemp") {
		data1$variable[i] <- "Future"
	}
}
# loop not working :( , guess it's not necessary

nrow(data1)
data2 <- na.omit(data1) #omitting NAs that will throw off my graph
nrow(data2)

theme_katie<-function(base_size = 18, base_family = ""){
  theme_bw(base_size = base_size, base_family = base_family) %+replace% 
    theme(axis.text = element_text(size = rel(0.8),colour="black"),
          axis.ticks = element_line(colour = "black"),
    			legend.key = element_rect(fill="transparent", colour=NA),
    			panel.background = element_blank(),
    			legend.background = element_rect(fill="transparent", colour=NA),
          legend.position = "none",
          panel.border = element_rect(fill = NA, colour = NA), 
          panel.grid.major = element_line(colour = NA,size = 0), 
          panel.grid.minor = element_line(colour = NA,size = 0), 
          axis.line = element_line(colour ="black")
    )
} #function for a pretty ggplot that will be consistent with the rest of my plots

#making ggplot that will put all trends on the same graph
p1 <- ggplot(data2, aes(x = variable , y = value)) +
	theme_katie() + 
	geom_smooth(method='lm',se=F,size=0.2,aes(group=climtrend.code),color='grey') +
	labs(y='Temperature (Degrees Celsius)', x='Time Point') +
	ggtitle("Atlantic Canada") +
	geom_smooth(data=data2,aes(x=variable,y= value),method='lm',se=F,size=2,color='black') +
	scale_x_discrete(labels=c("Past (~1800)", "Present (~1950)", "Future (~2100)"))


print(p1)
ggsave("TempTrendsBIG.pdf")
```
Now to do the same thing with the NFL data:

```{r}
climtrendNFL <- read.csv("ClimTrendDataNFL4.csv")
head(climtrendNFL)

dataNFL <- data.frame(climtrendNFL$River, climtrendNFL$pastTemp, climtrendNFL$CurTemp, climtrendNFL$FutTemp)
View(dataNFL) #putting data columns I want for my graph into a data frame

dataNFL1 <- melt(dataNFL, id.vars=c("climtrendNFL.River")) #melting so that temperature is now a column, and timepoint is now a column
View(dataNFL1)

nrow(dataNFL1)
dataNFL2 <- na.omit(dataNFL1) #omitting NAs that will throw off my graph
nrow(dataNFL2)

p2 <- ggplot(dataNFL2, aes(x = variable , y = value)) +
	theme_katie() + 
	geom_smooth(method='lm',se=F,size=0.2,aes(group=climtrendNFL.River),color='grey') +
	labs(y='Temperature (Degrees Celsius)', x='Time Point') +
	ggtitle("Newfoundland") +
	geom_smooth(data=dataNFL2,aes(x=variable,y= value),method='lm',se=F,size=2,color='black') +
	scale_x_discrete(labels=c("Past (~1800)", "Present (~1950)", "Future (~2100)"))


print(p2)
ggsave("TempTrendsNFL.pdf")
```


